# Generated by Django 4.1.7 on 2023-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('translation', models.TextField()),
                ('added_date', models.TextField()),
                ('added_email', models.TextField()),
            ],
            options={
                'db_table': 'dictionary',
                'managed': False,
            },
        ),
    ]
